name: Forge Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts (optional but recommended)
        run: forge build --sizes

      - name: Generate docs
        run: |
          cd docs
          forge doc --out .

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Post-process HTML
        run: |
          node tools/doc-postprocess.mjs ./docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
