#!/bin/bash

# Quantillon Protocol - Contract Size Analysis Script
# Analyzes smart contract sizes against EIP-170 limit and logs results
#
# This script automatically discovers all contracts from the 'out/' directory
# (generated by 'forge build') and analyzes their deployed bytecode sizes.
# Test contracts (*.t.sol) are excluded by default.
#
# Features:
# - Automatic contract discovery (no hardcoded list)
# - Filters out abstract contracts (no deployed bytecode)
# - Excludes test contracts by default
# - Categorizes contracts by size (Critical/Warning/Safe)
# - Generates detailed reports

set -e

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse optional CLI arguments
LIMIT_PERCENT_CLI=""
while [ $# -gt 0 ]; do
    case "$1" in
        --limit-percent)
            shift
            if [ $# -eq 0 ]; then
                echo "Error: --limit-percent requires a value (1-100)" >&2
                exit 2
            fi
            LIMIT_PERCENT_CLI="$1"
            ;;
        --help|-h)
            cat <<EOF
Usage: $(basename "$0") [--limit-percent N]

Options:
  --limit-percent N   Personal contract-size budget as percentage of EIP-170 (1-100)
                      Also configurable via EIP170_PERSONAL_LIMIT_PERCENT env var.
                      CLI flag takes precedence over env var.
EOF
            exit 0
            ;;
        *)
            echo "Error: Unknown argument '$1'" >&2
            exit 2
            ;;
    esac
    shift
done

# Configuration
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load environment variables using shared utility
source "$(dirname "${BASH_SOURCE[0]}")/utils/load-env.sh"
setup_environment --allow-missing
OUTPUT_DIR="$PROJECT_ROOT/$RESULTS_DIR/contract-sizes"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
REPORT_FILE="$OUTPUT_DIR/contract-sizes-$TIMESTAMP.txt"
SUMMARY_FILE="$OUTPUT_DIR/contract-sizes-summary.txt"

# EIP-170 limit: 24KB = 24576 bytes
EIP170_LIMIT=24576
PERSONAL_LIMIT_PERCENT="${LIMIT_PERCENT_CLI:-${EIP170_PERSONAL_LIMIT_PERCENT:-100}}"

if ! [[ "$PERSONAL_LIMIT_PERCENT" =~ ^[0-9]+$ ]]; then
    echo "Error: personal limit percent must be an integer (1-100), got '$PERSONAL_LIMIT_PERCENT'" >&2
    exit 2
fi

if [ "$PERSONAL_LIMIT_PERCENT" -lt 1 ] || [ "$PERSONAL_LIMIT_PERCENT" -gt 100 ]; then
    echo "Error: personal limit percent must be between 1 and 100, got '$PERSONAL_LIMIT_PERCENT'" >&2
    exit 2
fi

PERSONAL_LIMIT_BYTES=$((EIP170_LIMIT * PERSONAL_LIMIT_PERCENT / 100))
PERSONAL_LIMIT_ALIGNS_WITH_EIP170="false"
if [ "$PERSONAL_LIMIT_BYTES" -ge "$EIP170_LIMIT" ]; then
    PERSONAL_LIMIT_ALIGNS_WITH_EIP170="true"
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo -e "${BLUE}🔍 QUANTILLON PROTOCOL - CONTRACT SIZE ANALYSIS${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "Generated: $(date)"
echo -e "EIP-170 Limit: $EIP170_LIMIT bytes (24KB)"
echo -e "Personal Limit: $PERSONAL_LIMIT_PERCENT% ($PERSONAL_LIMIT_BYTES bytes)"
echo -e "Project: Quantillon Protocol Smart Contracts"
echo ""

# Function to get contract size from JSON
get_contract_size() {
    local json_file="$1"
    if [ -f "$json_file" ]; then
        # Extract deployedBytecode size (remove 0x prefix and count characters)
        local bytecode=$(jq -r '.deployedBytecode.object' "$json_file" 2>/dev/null)
        if [ "$bytecode" != "null" ] && [ "$bytecode" != "" ]; then
            # Remove 0x prefix and count characters, then divide by 2 (each byte is 2 hex chars)
            local size=$(((${#bytecode} - 2) / 2))
            echo $size
        else
            echo "0"
        fi
    else
        echo "0"
    fi
}

# Function to format size
format_size() {
    local size=$1
    if [ $size -ge 1024 ]; then
        local kb_size=$(echo "scale=1; $size/1024" | bc -l | tr ',' '.')
        echo "${kb_size} KB"
    else
        echo "${size} bytes"
    fi
}

# Function to get percentage of limit
get_percentage() {
    local size=$1
    local limit=$2
    local percentage=$(echo "scale=1; $size*100/$limit" | bc -l | tr ',' '.')
    echo "${percentage}%"
}

# Function to discover all contracts automatically
# Scans the out/ directory for all compiled contracts
discover_contracts() {
    local out_dir="out"
    local exclude_tests="${1:-true}"  # Default: exclude test contracts
    
    if [ ! -d "$out_dir" ]; then
        echo "Error: $out_dir directory not found. Please run 'forge build' first." >&2
        return 1
    fi
    
    # Find all .sol directories in out/
    while IFS= read -r -d '' sol_dir; do
        # Extract contract file name (e.g., "HedgerPool.sol" from "out/HedgerPool.sol")
        local contract_file=$(basename "$sol_dir")
        
        # Skip test contracts if exclude_tests is true
        if [ "$exclude_tests" = "true" ] && [[ "$contract_file" == *.t.sol ]]; then
            continue
        fi
        
        # Skip build-info directory
        if [ "$contract_file" = "build-info" ]; then
            continue
        fi
        
        # Find all JSON files in this directory
        while IFS= read -r -d '' json_file; do
            local contract_name=$(basename "$json_file" .json)
            local json_path="$json_file"
            
            # Check if contract has deployed bytecode (size > 0)
            local size=$(get_contract_size "$json_path")
            if [ $size -gt 0 ]; then
                # Return format: contract_file:contract_name:json_path
                echo "$contract_file:$contract_name:$json_path"
            fi
        done < <(find "$sol_dir" -maxdepth 1 -name "*.json" -type f -print0 2>/dev/null)
    done < <(find "$out_dir" -maxdepth 1 -type d -name "*.sol" -print0 2>/dev/null)
}

# Initialize arrays
declare -a critical_contracts=()
declare -a personal_limit_contracts=()
declare -a warning_contracts=()
declare -a safe_contracts=()

total_size=0
contract_count=0

echo -e "${BLUE}📊 DISCOVERING AND ANALYZING SMART CONTRACTS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

# Check if forge build has been run
if [ ! -d "out" ]; then
    echo -e "${RED}Error: 'out' directory not found. Please run 'forge build' first.${NC}" >&2
    exit 1
fi

# Discover all contracts (excluding test contracts by default)
echo -e "Discovering contracts from out/ directory..."
discovered_contracts=$(discover_contracts true)
if [ -z "$discovered_contracts" ]; then
    echo -e "${YELLOW}Warning: No contracts with deployed bytecode found.${NC}"
    echo -e "This may indicate:"
    echo -e "  • Contracts haven't been built (run 'forge build')"
    echo -e "  • All contracts are abstract/interfaces (no bytecode)"
    exit 0
fi

# Analyze each discovered contract
while IFS= read -r contract_info; do
    if [ -z "$contract_info" ]; then
        continue
    fi
    
    contract_file=$(echo "$contract_info" | cut -d':' -f1)
    contract_name=$(echo "$contract_info" | cut -d':' -f2)
    json_file=$(echo "$contract_info" | cut -d':' -f3)
    
    size=$(get_contract_size "$json_file")
    
    if [ $size -gt 0 ]; then
        total_size=$((total_size + size))
        contract_count=$((contract_count + 1))
        
        percentage=$(get_percentage $size $EIP170_LIMIT)
        formatted_size=$(format_size $size)
        
        # Categorize contracts
        if [ $size -gt $EIP170_LIMIT ]; then
            critical_contracts+=("$contract_name:$size:$percentage")
            echo -e "${RED}❌ $contract_name - $formatted_size ($percentage of limit) - EXCEEDS LIMIT${NC}"
        elif [ $size -gt $PERSONAL_LIMIT_BYTES ]; then
            personal_limit_contracts+=("$contract_name:$size:$percentage")
            echo -e "${RED}⛔ $contract_name - $formatted_size ($percentage of limit) - EXCEEDS PERSONAL LIMIT (${PERSONAL_LIMIT_PERCENT}%)${NC}"
        elif [ $size -gt $((EIP170_LIMIT * 80 / 100)) ]; then
            warning_contracts+=("$contract_name:$size:$percentage")
            echo -e "${YELLOW}⚠️  $contract_name - $formatted_size ($percentage of limit) - WARNING${NC}"
        else
            safe_contracts+=("$contract_name:$size:$percentage")
            echo -e "${GREEN}✓ $contract_name - $formatted_size ($percentage of limit) - SAFE${NC}"
        fi
    fi
done <<< "$discovered_contracts"

echo ""
total_personal_limit_breaches=$(( ${#critical_contracts[@]} + ${#personal_limit_contracts[@]} ))

# Generate summary statistics
echo ""
echo -e "${BLUE}📈 SUMMARY STATISTICS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [ $contract_count -gt 0 ]; then
    echo -e "Total Contracts Analyzed: $contract_count"
    echo -e "Total Combined Size: $(format_size $total_size)"
    avg_size=$((total_size / contract_count))
    echo -e "Average Contract Size: $(format_size $avg_size)"
    echo -e "Personal Limit Breaches (total, incl. critical): $total_personal_limit_breaches"
else
    echo -e "${YELLOW}No contracts found to analyze${NC}"
fi
echo ""

# Critical contracts section
echo -e "${RED}🔴 CRITICAL CONTRACTS (Exceed EIP-170 Limit)${NC}"
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [ ${#critical_contracts[@]} -eq 0 ]; then
    echo -e " No contracts exceed the EIP-170 limit!"
else
    for contract_info in "${critical_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo -e " $contract_name - $formatted_size ($percentage of limit)"
    done
fi

echo ""

# Personal limit contracts section
echo -e "${RED}⛔ PERSONAL LIMIT CONTRACTS (Above ${PERSONAL_LIMIT_PERCENT}% of EIP-170, excluding EIP-170 critical breaches)${NC}"
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [ "$PERSONAL_LIMIT_ALIGNS_WITH_EIP170" = "true" ]; then
    echo -e " Personal limit is aligned with EIP-170 (${PERSONAL_LIMIT_PERCENT}%)."
    echo -e " Contracts above this threshold are reported in the CRITICAL section."
elif [ ${#personal_limit_contracts[@]} -eq 0 ]; then
    echo -e " No non-critical contracts exceed the personal limit."
else
    for contract_info in "${personal_limit_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo -e " $contract_name - $formatted_size ($percentage of limit)"
    done
fi

echo ""

# Warning contracts section
echo -e "${YELLOW}⚠️  WARNING CONTRACTS (80%+ of EIP-170 Limit)${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [ ${#warning_contracts[@]} -eq 0 ]; then
    echo -e " No contracts in warning zone!"
else
    for contract_info in "${warning_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo -e "  $contract_name - $formatted_size ($percentage of limit)"
    done
fi

echo ""

# Safe contracts section
echo -e "${GREEN}✓ SAFE CONTRACTS (Under 80% of EIP-170 Limit)${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [ ${#safe_contracts[@]} -eq 0 ]; then
    echo -e "  No contracts in safe zone"
else
    for contract_info in "${safe_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo -e " $contract_name - $formatted_size ($percentage of limit)"
    done
fi

echo ""

# Recommendations section
echo -e "${BLUE}💡 RECOMMENDATIONS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

if [ ${#critical_contracts[@]} -gt 0 ]; then
    echo -e "${RED}🔴 CRITICAL: Contracts exceeding EIP-170 limit must be refactored:${NC}"
    echo -e "   • Split large contracts into smaller modules"
    echo -e "   • Move complex logic to libraries"
    echo -e "   • Use proxy patterns for upgradeability"
    echo -e "   • Remove unused code and optimize imports"
    echo ""
fi

if [ ${#personal_limit_contracts[@]} -gt 0 ]; then
    echo -e "${RED}⛔ PERSONAL LIMIT: Contracts above ${PERSONAL_LIMIT_PERCENT}% of EIP-170 require optimization:${NC}"
    echo -e "   • Move heavy logic to libraries"
    echo -e "   • Remove non-essential view/helpers from hot contracts"
    echo -e "   • Re-check with --sizes after each refactor"
    echo ""
elif [ "$PERSONAL_LIMIT_ALIGNS_WITH_EIP170" = "true" ] && [ ${#critical_contracts[@]} -gt 0 ]; then
    echo -e "${RED}⛔ PERSONAL LIMIT: Personal limit aligns with EIP-170; see CRITICAL section for all breaches.${NC}"
    echo ""
fi

if [ ${#warning_contracts[@]} -gt 0 ]; then
    echo -e "${YELLOW}⚠️  WARNING: Contracts approaching limit should be monitored:${NC}"
    echo -e "   • Consider refactoring before adding new features"
    echo -e "   • Optimize existing code"
    echo -e "   • Move non-critical functions to libraries"
    echo ""
fi

if [ ${#critical_contracts[@]} -eq 0 ] && [ ${#warning_contracts[@]} -eq 0 ]; then
    echo -e "${GREEN}✓ All contracts are within safe limits!${NC}"
    echo -e "   • Continue monitoring as you add features"
    echo -e "   • Consider size optimization for gas efficiency"
fi

# Save detailed report to file
{
    echo "QUANTILLON PROTOCOL - CONTRACT SIZE ANALYSIS REPORT"
    echo "Generated: $(date)"
    echo "EIP-170 Limit: $EIP170_LIMIT bytes (24KB)"
    echo "Personal Limit: $PERSONAL_LIMIT_PERCENT% ($PERSONAL_LIMIT_BYTES bytes)"
    echo "Project: Quantillon Protocol Smart Contracts"
    echo ""
    echo "EXECUTIVE SUMMARY"
    if [ $contract_count -gt 0 ]; then
        echo "Total Contracts Analyzed: $contract_count"
        echo "Total Combined Size: $(format_size $total_size)"
        avg_size=$((total_size / contract_count))
        echo "Average Contract Size: $(format_size $avg_size)"
        echo "Personal Limit Breaches Total (including critical): $total_personal_limit_breaches"
    else
        echo "Total Contracts Analyzed: 0"
        echo "No contracts with deployed bytecode found"
    fi
    echo ""
    echo "CRITICAL CONTRACTS (Exceed EIP-170 Limit): ${#critical_contracts[@]}"
    for contract_info in "${critical_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo "  - $contract_name: $formatted_size ($percentage of limit)"
    done
    echo ""
    echo "PERSONAL LIMIT CONTRACTS (Above ${PERSONAL_LIMIT_PERCENT}% of EIP-170, excluding EIP-170 critical breaches): ${#personal_limit_contracts[@]}"
    echo "PERSONAL LIMIT BREACHES TOTAL (including critical): $total_personal_limit_breaches"
    for contract_info in "${personal_limit_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo "  - $contract_name: $formatted_size ($percentage of limit)"
    done
    echo ""
    echo "WARNING CONTRACTS (80%+ of EIP-170 Limit): ${#warning_contracts[@]}"
    for contract_info in "${warning_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo "  - $contract_name: $formatted_size ($percentage of limit)"
    done
    echo ""
    echo "SAFE CONTRACTS (Under 80% of EIP-170 Limit): ${#safe_contracts[@]}"
    for contract_info in "${safe_contracts[@]}"; do
        contract_name=$(echo "$contract_info" | cut -d':' -f1)
        size=$(echo "$contract_info" | cut -d':' -f2)
        percentage=$(echo "$contract_info" | cut -d':' -f3)
        formatted_size=$(format_size $size)
        echo "  - $contract_name: $formatted_size ($percentage of limit)"
    done
} > "$REPORT_FILE"

# Save summary to file
{
    echo "Contract Size Analysis Summary - $(date)"
    echo "========================================"
    echo "Personal Limit: $PERSONAL_LIMIT_PERCENT% ($PERSONAL_LIMIT_BYTES bytes)"
    echo "Critical Contracts: ${#critical_contracts[@]}"
    echo "Personal Limit Breaches (non-critical): ${#personal_limit_contracts[@]}"
    echo "Personal Limit Breaches Total (including critical): $total_personal_limit_breaches"
    echo "Warning Contracts: ${#warning_contracts[@]}"
    echo "Safe Contracts: ${#safe_contracts[@]}"
    echo "Total Size: $(format_size $total_size)"
    echo ""
    if [ ${#critical_contracts[@]} -gt 0 ]; then
        echo "CRITICAL:"
        for contract_info in "${critical_contracts[@]}"; do
            contract_name=$(echo "$contract_info" | cut -d':' -f1)
            percentage=$(echo "$contract_info" | cut -d':' -f3)
            echo "  - $contract_name ($percentage of limit)"
        done
    fi
    if [ ${#warning_contracts[@]} -gt 0 ]; then
        echo "WARNING:"
        for contract_info in "${warning_contracts[@]}"; do
            contract_name=$(echo "$contract_info" | cut -d':' -f1)
            percentage=$(echo "$contract_info" | cut -d':' -f3)
            echo "  - $contract_name ($percentage of limit)"
        done
    fi
    if [ ${#personal_limit_contracts[@]} -gt 0 ]; then
        echo "PERSONAL LIMIT BREACHES (non-critical):"
        for contract_info in "${personal_limit_contracts[@]}"; do
            contract_name=$(echo "$contract_info" | cut -d':' -f1)
            percentage=$(echo "$contract_info" | cut -d':' -f3)
            echo "  - $contract_name ($percentage of limit)"
        done
    elif [ "$PERSONAL_LIMIT_ALIGNS_WITH_EIP170" = "true" ] && [ ${#critical_contracts[@]} -gt 0 ]; then
        echo "PERSONAL LIMIT BREACHES (non-critical): none (personal limit aligns with EIP-170)"
        echo "PERSONAL LIMIT BREACHES (critical):"
        for contract_info in "${critical_contracts[@]}"; do
            contract_name=$(echo "$contract_info" | cut -d':' -f1)
            percentage=$(echo "$contract_info" | cut -d':' -f3)
            echo "  - $contract_name ($percentage of limit)"
        done
    fi
} > "$SUMMARY_FILE"

echo ""
echo -e "${GREEN}🎯 Contract size analysis complete!${NC}"
echo -e "   Detailed report: $REPORT_FILE"
echo -e "   Summary report: $SUMMARY_FILE"

# Exit with error code if critical contracts found
if [ ${#critical_contracts[@]} -gt 0 ] || [ ${#personal_limit_contracts[@]} -gt 0 ]; then
    if [ ${#critical_contracts[@]} -gt 0 ] && [ ${#personal_limit_contracts[@]} -gt 0 ]; then
        echo -e "${RED}❌ Analysis failed: ${#critical_contracts[@]} contracts exceed EIP-170 and ${#personal_limit_contracts[@]} exceed personal limit (${PERSONAL_LIMIT_PERCENT}%)${NC}"
    elif [ ${#critical_contracts[@]} -gt 0 ]; then
        if [ "$PERSONAL_LIMIT_ALIGNS_WITH_EIP170" = "true" ]; then
            echo -e "${RED}❌ Analysis failed: ${#critical_contracts[@]} contracts exceed EIP-170 limit (personal limit ${PERSONAL_LIMIT_PERCENT}% aligns with EIP-170)${NC}"
        else
            echo -e "${RED}❌ Analysis failed: ${#critical_contracts[@]} contracts exceed EIP-170 limit${NC}"
        fi
    else
        echo -e "${RED}❌ Analysis failed: ${#personal_limit_contracts[@]} contracts exceed personal limit (${PERSONAL_LIMIT_PERCENT}% of EIP-170)${NC}"
    fi
    exit 1
else
    echo -e "${GREEN}✓ All contracts within personal and EIP-170 limits${NC}"
    exit 0
fi
