name: Notify Telegram on Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          BRANCH="${{ github.ref_name }}"
          REPO_NAME="${{ github.repository }}"
          
          MESSAGE="🚀 New commit on \`$REPO_NAME\` (\`$BRANCH\` branch)
          
          📝 Commit: $COMMIT_MESSAGE
          🔗 URL: $COMMIT_URL
          
          👤 Author: ${{ github.event.head_commit.author.name }}"
          
          curl -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d "chat_id=$CHANNEL_ID" \
            -d "text=$MESSAGE" \
            -d "parse_mode=Markdown"
